# -*- coding: utf-8 -*-
"""
MeetIt yasal metinleri — TEK KAYNAK.

Bu dosyadaki metinler hem uygulama içi sayfalara (assets/translations/*.json,
legal.* anahtarları) hem de web sayfalarına (legal/terms.html,
legal/privacy.html) basılır. Metni değiştirmek için SADECE burayı düzenle,
sonra:   python3 legal/build_legal.py
"""
CONTACT = "hafifsaglam61@gmail.com"
OWNER = "Ahmet Salih Kocatürk"
UPDATED = {"tr": "28 Eylül 2026", "en": "September 28, 2026"}

TERMS = {
"tr": [
("1. Taraflar ve Kabul",
 f"Bu Kullanım Koşulları, MeetIt mobil uygulamasını (\"Uygulama\") geliştiren ve işleten {OWNER} (\"MeetIt\", \"biz\") ile Uygulamayı kullanan sen arasındaki ilişkiyi düzenler. Hesap oluşturarak veya Uygulamayı kullanarak bu Koşulları ve Gizlilik Politikası'nı kabul etmiş olursun. Kabul etmiyorsan Uygulamayı kullanmamalısın."),
("2. Yaş Sınırı ve Hesap",
 "Uygulama yalnızca 18 yaşını doldurmuş kişiler içindir; 18 yaşından küçükler Uygulamayı kullanamaz ve hesap açamaz. Kayıt sırasında doğru bilgi vermekten, hesabının ve giriş bilgilerinin güvenliğinden sen sorumlusun. Başkası adına veya sahte bir kimlikle hesap açılamaz."),
("3. Hizmetin Kapsamı",
 "MeetIt; arkadaşlarınla aranızdaki orta noktaya yakın mekanlar önermeyi, kişilik profiline göre öneriler sunmayı, mekanlara yorum ve puan bırakmayı ve arkadaş eklemeyi sağlar. Mekan bilgileri (ad, adres, puan, fotoğraf, çalışma saatleri vb.) büyük ölçüde Google gibi üçüncü taraf kaynaklardan gelir; doğruluğu, güncelliği ve mekanların uygunluğu garanti edilmez. Uygulamanın özellikleri değiştirilebilir veya sonlandırılabilir."),
("4. Kullanıcı İçeriği ve Yasak Davranışlar",
 "Uygulamada paylaştığın ad, profil fotoğrafı, yorum, puan ve fotoğraflardan sen sorumlusun. Aşağıdakiler kesinlikle yasaktır:\n• yasa dışı içerik\n• taciz, zorbalık, tehdit, hakaret, nefret söylemi veya ayrımcılık\n• müstehcen, cinsel veya şiddet içeren içerik\n• başkalarının kişisel bilgilerini izinsiz paylaşmak\n• sahte profil veya kimlik taklidi\n• spam, dolandırıcılık, oltalama veya zararlı yazılım\n• başkalarının fikri mülkiyet haklarını ihlal etmek\n• Uygulamanın güvenliğini veya işleyişini bozmaya çalışmak"),
("5. Sıfır Tolerans, Şikâyet ve Engelleme",
 f"MeetIt, uygunsuz içeriğe ve taciz eden kullanıcılara karşı sıfır tolerans uygular.\n• Şikâyet: bir kullanıcının profilinde sağ üstteki menüden \"Şikâyet Et\"i, bir mekan yorumunda ise şikâyet simgesini kullanabilirsin.\n• Engelleme: aynı menüdeki \"Engelle\" ile ya da sana gelen bir arkadaşlık isteğindeki engelle simgesiyle bir kullanıcıyı engelleyebilirsin. Engellenen kişi arkadaş listenden çıkarılır, sana bir daha arkadaşlık isteği gönderemez ve iki taraf da birbirini listelerde göremez.\n• Şikâyetler 24 saat içinde incelenir. Bu Koşulları ihlal eden içerik kaldırılır ve içeriği paylaşan kullanıcının hesabı kapatılır. Bu tür ihlaller için düzeltme süresi tanınmaz.\n• Gerekli durumlarda yetkili makamlarla iş birliği yapılır.\nŞikâyetlerini {CONTACT} adresine de iletebilirsin."),
("6. Buluşmalar ve Kişisel Güvenlik",
 "MeetIt kullanıcıların kimliğini doğrulamaz ve kullanıcıların davranışlarından sorumlu değildir. Buluşmalarını kendi sorumluluğunda gerçekleştirirsin. Tanımadığın kişilerle buluşurken kalabalık ve halka açık yerleri tercih etmeni ve bir yakınını bilgilendirmeni öneririz. Acil durumda 112'yi ara."),
("7. Fikri Mülkiyet ve İçerik Lisansı",
 "Uygulamanın yazılımı, tasarımı, logosu ve markası dahil tüm fikri mülkiyet hakları MeetIt'e aittir. Paylaştığın içeriklerin haklarına sahip olmaya devam edersin; bu içerikleri Uygulama içinde göstermemiz, saklamamız ve işlememiz için bize ücretsiz ve münhasır olmayan bir kullanım izni verirsin. Bu izin, içeriği veya hesabını sildiğinde sona erer."),
("8. Reklamlar ve Üçüncü Taraf Hizmetler",
 "Uygulama, Google AdMob üzerinden reklam gösterir ve Google ile Apple gibi üçüncü taraf hizmetlerini kullanır. Bu hizmetlerin kendi koşulları ve gizlilik politikaları da geçerlidir. Reklam verenlerin ürün ve hizmetlerinden MeetIt sorumlu değildir."),
("9. Uygulama Mağazaları",
 "Bu Koşullar yalnızca seninle MeetIt arasındadır. Apple ve Google bu Koşulların tarafı değildir ve Uygulamanın içeriğinden, bakımından veya desteğinden sorumlu değildir. Uygulamayı indirdiğin mağazanın kullanım koşulları da geçerlidir."),
("10. Sorumluluğun Sınırlandırılması",
 "Uygulama \"olduğu gibi\" sunulur; kesintisiz veya hatasız çalışacağı garanti edilmez. Yürürlükteki mevzuatın izin verdiği ölçüde MeetIt; kullanıcılar arasındaki etkileşimlerden, buluşmalardan, mekanlardan ve üçüncü taraf hizmetlerden doğan zararlardan ve dolaylı zararlardan sorumlu değildir. Kasıt ve ağır ihmalden doğan sorumluluk ile tüketici mevzuatından doğan emredici hakların saklıdır."),
("11. Hesabın Sona Ermesi",
 "Hesabını dilediğin zaman Ayarlar > Hesabı Sil yoluyla silebilirsin; bu durumda verilerin Gizlilik Politikası'nda anlatıldığı şekilde silinir. MeetIt, bu Koşulları ihlal eden hesapları önceden bildirimde bulunmaksızın askıya alabilir veya kapatabilir."),
("12. Değişiklikler",
 "Bu Koşullar zaman zaman güncellenebilir. Önemli değişiklikler Uygulama içinden duyurulur. Değişiklikten sonra Uygulamayı kullanmaya devam etmen, güncel Koşulları kabul ettiğin anlamına gelir."),
("13. Uygulanacak Hukuk ve Uyuşmazlıklar",
 "Bu Koşullar Türkiye Cumhuriyeti hukukuna tabidir. Uyuşmazlıklarda İstanbul Merkez Mahkemeleri ve İcra Daireleri yetkilidir. Tüketici mevzuatından doğan başvuru hakların (tüketici hakem heyetleri ve tüketici mahkemeleri) saklıdır."),
("14. İletişim", f"Sorular ve talepler için: {CONTACT}"),
],
"en": [
("1. Parties and Acceptance",
 f"These Terms of Use govern the relationship between you and {OWNER} (\"MeetIt\", \"we\"), who develops and operates the MeetIt mobile application (the \"App\"). By creating an account or using the App, you accept these Terms and the Privacy Policy. If you do not accept them, do not use the App."),
("2. Age Requirement and Account",
 "The App is only for people who are 18 years of age or older; anyone under 18 may not use the App or create an account. You are responsible for providing accurate information and for the security of your account and sign-in credentials. You may not create an account on behalf of someone else or under a false identity."),
("3. The Service",
 "MeetIt suggests venues near the midpoint between you and your friends, offers recommendations based on your personality profile, lets you review and rate venues, and lets you add friends. Venue information (name, address, rating, photos, opening hours, etc.) largely comes from third-party sources such as Google; its accuracy, timeliness and the suitability of venues are not guaranteed. Features of the App may change or be discontinued."),
("4. User Content and Prohibited Conduct",
 "You are responsible for the name, profile photo, reviews, ratings and photos you share in the App. The following are strictly prohibited:\n• illegal content\n• harassment, bullying, threats, insults, hate speech or discrimination\n• obscene, sexual or violent content\n• sharing other people's personal information without permission\n• fake profiles or impersonation\n• spam, fraud, phishing or malware\n• infringing others' intellectual property rights\n• attempting to compromise the security or operation of the App"),
("5. Zero Tolerance, Reporting and Blocking",
 f"MeetIt has zero tolerance for objectionable content and abusive users.\n• Reporting: use \"Şikâyet Et\" (Report) in the menu at the top right of a user's profile, or the report icon on a venue review.\n• Blocking: use \"Engelle\" (Block) in the same menu, or the block icon on an incoming friend request. The blocked person is removed from your friends list, can no longer send you friend requests, and neither of you will see the other in any list.\n• Reports are reviewed within 24 hours. Content that violates these Terms is removed and the account of the user who posted it is terminated. No cure period is given for such violations.\n• Where necessary, we cooperate with the competent authorities.\nYou can also send reports to {CONTACT}."),
("6. Meetups and Personal Safety",
 "MeetIt does not verify users' identities and is not responsible for users' conduct. You attend meetups at your own responsibility. When meeting people you do not know, we recommend choosing busy, public places and letting someone you trust know. In an emergency, call your local emergency number (112 in Türkiye)."),
("7. Intellectual Property and Content License",
 "All intellectual property rights in the App, including its software, design, logo and brand, belong to MeetIt. You keep the rights to the content you share; you grant us a free, non-exclusive license to display, store and process that content within the App. This license ends when you delete the content or your account."),
("8. Ads and Third-Party Services",
 "The App shows ads through Google AdMob and uses third-party services such as Google and Apple. The terms and privacy policies of those services also apply. MeetIt is not responsible for advertisers' products or services."),
("9. App Stores",
 "These Terms are between you and MeetIt only. Apple and Google are not parties to these Terms and are not responsible for the App, its content, maintenance or support. The terms of the store you downloaded the App from also apply."),
("10. Limitation of Liability",
 "The App is provided \"as is\"; we do not guarantee that it will be uninterrupted or error-free. To the extent permitted by applicable law, MeetIt is not liable for damages arising from interactions between users, meetups, venues or third-party services, or for indirect damages. Liability for intent and gross negligence, and your mandatory rights under consumer law, remain unaffected."),
("11. Termination",
 "You can delete your account at any time via Settings > Delete Account (Ayarlar > Hesabı Sil); your data is then deleted as described in the Privacy Policy. MeetIt may suspend or terminate accounts that violate these Terms without prior notice."),
("12. Changes",
 "These Terms may be updated from time to time. Significant changes are announced in the App. Continuing to use the App after a change means you accept the updated Terms."),
("13. Governing Law and Disputes",
 "These Terms are governed by the laws of the Republic of Türkiye. The courts and enforcement offices of Istanbul (Central) have jurisdiction over disputes. Your rights to apply to consumer arbitration committees and consumer courts under consumer law remain reserved."),
("14. Contact", f"For questions and requests: {CONTACT}"),
],
}

PRIVACY = {
"tr": [
("1. Veri Sorumlusu",
 f"Bu Gizlilik Politikası, MeetIt mobil uygulamasını kullanırken kişisel verilerinin nasıl işlendiğini açıklar ve 6698 sayılı Kişisel Verilerin Korunması Kanunu (\"KVKK\") kapsamında aydınlatma metni niteliğindedir.\nVeri sorumlusu: {OWNER}\nİletişim: {CONTACT}"),
("2. Topladığımız Veriler",
 "• Hesap bilgileri: ad soyad, e-posta adresi, profil fotoğrafı; Google veya Apple ile girişte bu hizmetlerin paylaştığı ad ve e-posta.\n• İsteğe bağlı profil bilgileri: yaş, cinsiyet, şehir/ilçe ve kayıtlı konumunun koordinatları. Bu alanları doldurmak zorunlu değildir.\n• 18 yaş teyidi ile Kullanım Koşulları ve Gizlilik Politikası onayların.\n• Kişilik testi sonucun, buna göre oluşan kişilik profilin ve bu profilin zaman içindeki değişimi.\n• Sosyal veriler: arkadaşların, arkadaşlık istekleri ve arkadaş kodun.\n• Paylaştığın içerikler: mekan yorumları, puanlar, yorum fotoğrafları ve beğeniler.\n• Kullanım verileri: kaydettiğin mekanlar, yol tarifi aldığın mekanlar, buluşma aramaların ve buluşma geçmişin.\n• Güvenlik verileri: yaptığın veya hakkında yapılan şikâyetler (şikâyet eden, şikâyet edilen, sebep, tarih) ve engellemeler.\n• Teknik veriler: bildirim (push) token'ı, cihaz ve işletim sistemi bilgileri, IP adresi, uygulama bütünlüğü doğrulaması (Firebase App Check) ve izin verdiysen reklam kimliği."),
("3. Toplama Yöntemi, Amaçlar ve Hukuki Sebepler",
 "Verilerin; uygulamaya girdiğin bilgilerden, Google ve Apple giriş hizmetlerinden ve uygulamanın çalışması sırasında otomatik olarak toplanır. Bu verileri şu amaçlarla işleriz:\n• hesabını oluşturmak ve yönetmek\n• arkadaşlarınla aranızdaki orta noktaya yakın mekanları önermek\n• kişilik profiline göre kişiselleştirilmiş öneriler sunmak (kişilik profilin, yorumlarına göre otomatik olarak güncellenir)\n• arkadaşlık istekleri ve buluşma davetleri için bildirim göndermek\n• şikâyetleri incelemek, kötüye kullanımı ve dolandırıcılığı önlemek, uygulamanın güvenliğini sağlamak\n• reklam göstermek ve yasal yükümlülükleri yerine getirmek\nHukuki sebepler (KVKK md. 5): sözleşmenin kurulması ve ifası, meşru menfaat (güvenlik ve moderasyon), hukuki yükümlülüklerin yerine getirilmesi ve gerekli hâllerde açık rızan (kişiselleştirilmiş reklamlar ve yurt dışına aktarım)."),
("4. Konum Verisi",
 "Konum yalnızca uygulama açıkken ve iznin varsa kullanılır; arka planda konum takibi yapılmaz. Konumunu haritadan seçebilir veya cihazının konumunu kullanabilirsin. Kayıtlı konumun, arkadaşlarınla aranızdaki orta noktayı hesaplamak ve yakındaki mekanları listelemek için kullanılır. Konum izni vermek zorunlu değildir; vermezsen konumunu haritadan elle seçebilirsin."),
("5. Diğer Kullanıcıların Görebildikleri",
 "• Adın, profil fotoğrafın ve kişilik tipin arkadaşlarına görünür; arkadaş önerilerinde ve arkadaş koduyla yapılan aramalarda diğer kullanıcılara da görünebilir.\n• Kayıtlı konumun, bir arkadaşınla buluşma noktası aranırken o arkadaşınla paylaşılır ve haritada gösterilebilir.\n• Mekan yorumların, puanların ve yorum fotoğrafların; adın ve profil fotoğrafınla birlikte tüm kullanıcılara görünür.\n• E-posta adresin diğer kullanıcılarla paylaşılmaz."),
("6. Hizmet Sağlayıcılar",
 "Verilerin satılmaz veya kiralanmaz. Uygulamanın çalışması için yalnızca şu hizmet sağlayıcılarla paylaşılır:\n• Google Firebase (Authentication, Cloud Firestore, Cloud Storage, Cloud Functions, Cloud Messaging, App Check): hesap, veri depolama, bildirimler ve güvenlik.\n• Google Maps Platform (Maps SDK, Places API): harita ve mekan bilgileri; mekan aramalarında konum koordinatları Google'a iletilir.\n• Google ile Giriş ve Apple ile Giriş: kimlik doğrulama.\n• Google AdMob: reklam gösterimi.\n• Apple Push Notification service: iOS'ta bildirimlerin iletilmesi.\nAyrıca yasal zorunluluk hâlinde yetkili kamu kurum ve kuruluşlarıyla paylaşılabilir."),
("7. Yurt Dışına Aktarım",
 "Yukarıdaki hizmet sağlayıcıların sunucuları başta ABD olmak üzere yurt dışında bulunduğundan kişisel verilerin yurt dışına aktarılır. Bu aktarım, KVKK'nın 9. maddesine uygun olarak ve gerekli hâllerde açık rızana dayanılarak yapılır."),
("8. Reklamlar ve Takip",
 "MeetIt, Google AdMob üzerinden reklam gösterir. iOS'ta uygulama ilk açılışta uygulamalar arası takip için izin ister (App Tracking Transparency). İzin verirsen reklam kimliğin kişiselleştirilmiş reklamlar için kullanılabilir; vermezsen kişiselleştirilmemiş reklamlar gösterilir ve tüm özellikler çalışmaya devam eder. Bu tercihi cihazının ayarlarından istediğin zaman değiştirebilirsin. Uygulama içi satın alma yoktur."),
("9. Saklama Süresi ve Hesap Silme",
 f"Verilerin, hesabın açık olduğu sürece saklanır. Hesabını Ayarlar > Hesabı Sil yoluyla istediğin zaman silebilirsin. Hesabını sildiğinde profilin, kayıtlı konumun, kişilik profilin, arkadaşlıkların, yorumların ve yorum fotoğrafların, beğenilerin, kaydettiğin mekanlar, buluşma geçmişin, engellemelerin ve bildirim verilerin kalıcı olarak silinir. Şikâyet kayıtları, moderasyon ve olası hukuki talepler için gerekli olan süre boyunca, en fazla 2 yıl saklanır. Silme talebini {CONTACT} adresine de iletebilirsin."),
("10. Güvenlik",
 "Verilerin, Google altyapısında aktarım sırasında ve depolamada şifrelenir; erişim, veritabanı güvenlik kuralları ve uygulama bütünlüğü doğrulamasıyla sınırlandırılır. Hiçbir yöntem tam güvenlik sağlayamasa da verilerini korumak için makul teknik ve idari tedbirleri alırız. Bir veri ihlali olursa, mevzuatın öngördüğü şekilde seni ve Kişisel Verileri Koruma Kurulu'nu bilgilendiririz."),
("11. Çocuklar",
 "MeetIt 18 yaşından küçükler için değildir ve bilerek 18 yaşından küçüklerin verilerini toplamaz. 18 yaşından küçük bir kullanıcının hesap açtığını öğrenirsek hesabı ve verilerini sileriz."),
("12. Hakların",
 f"KVKK'nın 11. maddesi uyarınca şu haklara sahipsin: verilerinin işlenip işlenmediğini öğrenme; işlenmişse bilgi talep etme; işlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme; yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme; eksik veya yanlış işlenmişse düzeltilmesini isteme; silinmesini veya yok edilmesini isteme; bu işlemlerin aktarıldığı üçüncü kişilere bildirilmesini isteme; otomatik sistemlerle analiz edilmesi sonucu aleyhine bir sonuç çıkmasına itiraz etme; kanuna aykırı işleme nedeniyle zarara uğrarsan zararın giderilmesini talep etme.\nTaleplerini {CONTACT} adresine iletebilirsin; en geç 30 gün içinde yanıtlarız. Yanıtımızdan memnun kalmazsan Kişisel Verileri Koruma Kurulu'na şikâyette bulunabilirsin."),
("13. Değişiklikler ve İletişim",
 f"Bu politika zaman zaman güncellenebilir; önemli değişiklikler uygulama içinden duyurulur. Sorular için: {CONTACT}"),
],
"en": [
("1. Data Controller",
 f"This Privacy Policy explains how your personal data is processed when you use the MeetIt mobile application. For users in Türkiye, it also serves as the information notice under the Personal Data Protection Law No. 6698 (\"KVKK\").\nData controller: {OWNER}\nContact: {CONTACT}"),
("2. Data We Collect",
 "• Account data: full name, email address, profile photo; when you sign in with Google or Apple, the name and email shared by those services.\n• Optional profile data: age, gender, city/district and the coordinates of your saved location. Filling in these fields is not required.\n• Your 18+ confirmation and your acceptance of the Terms of Use and the Privacy Policy.\n• Your personality test result, the resulting personality profile and how it changes over time.\n• Social data: your friends, friend requests and your friend code.\n• Content you share: venue reviews, ratings, review photos and likes.\n• Usage data: venues you save, venues you get directions to, your meetup searches and meetup history.\n• Safety data: reports you make or that are made about you (reporter, reported user, reason, date) and blocks.\n• Technical data: push notification token, device and operating system information, IP address, app integrity checks (Firebase App Check) and, if you allow it, your advertising identifier."),
("3. How We Collect Data, Purposes and Legal Bases",
 "Your data is collected from the information you enter in the app, from the Google and Apple sign-in services, and automatically while the app runs. We process it to:\n• create and manage your account\n• suggest venues near the midpoint between you and your friends\n• provide personalized recommendations based on your personality profile (your profile is updated automatically based on your reviews)\n• send notifications for friend requests and meetup invitations\n• review reports, prevent abuse and fraud, and keep the app secure\n• show ads and comply with legal obligations\nLegal bases (KVKK art. 5): performance of a contract, legitimate interest (security and moderation), compliance with legal obligations and, where required, your explicit consent (personalized ads and international transfers)."),
("4. Location Data",
 "Location is used only while the app is open and only with your permission; there is no background location tracking. You can pick your location on the map or use your device location. Your saved location is used to compute the midpoint between you and your friends and to list nearby venues. Granting location permission is optional; if you decline, you can pick your location on the map manually."),
("5. What Other Users Can See",
 "• Your name, profile photo and personality type are visible to your friends and may be visible to other users in friend suggestions and friend-code searches.\n• Your saved location is shared with a friend when you search for a meeting spot with that friend and may be shown on the map.\n• Your venue reviews, ratings and review photos are visible to all users together with your name and profile photo.\n• Your email address is not shared with other users."),
("6. Service Providers",
 "Your data is never sold or rented. It is shared only with the following service providers so the app can work:\n• Google Firebase (Authentication, Cloud Firestore, Cloud Storage, Cloud Functions, Cloud Messaging, App Check): accounts, data storage, notifications and security.\n• Google Maps Platform (Maps SDK, Places API): maps and venue information; location coordinates are sent to Google in venue searches.\n• Sign in with Google and Sign in with Apple: authentication.\n• Google AdMob: ads.\n• Apple Push Notification service: delivering notifications on iOS.\nData may also be disclosed to competent public authorities where required by law."),
("7. International Transfers",
 "Because the servers of the service providers above are located abroad, primarily in the United States, your personal data is transferred outside Türkiye. These transfers are carried out in accordance with Article 9 of the KVKK and, where required, on the basis of your explicit consent."),
("8. Ads and Tracking",
 "MeetIt shows ads through Google AdMob. On iOS, the app asks for permission to track across apps (App Tracking Transparency) on first launch. If you allow it, your advertising identifier may be used for personalized ads; if you decline, non-personalized ads are shown and every feature keeps working. You can change this choice at any time in your device settings. There are no in-app purchases."),
("9. Retention and Account Deletion",
 f"Your data is kept while your account is active. You can delete your account at any time via Settings > Delete Account (Ayarlar > Hesabı Sil). When you delete your account, your profile, saved location, personality profile, friendships, reviews and review photos, likes, saved venues, meetup history, blocks and notification data are permanently deleted. Report records are kept for as long as necessary for moderation and possible legal claims, for at most 2 years. You can also send a deletion request to {CONTACT}."),
("10. Security",
 "Your data is encrypted in transit and at rest on Google's infrastructure, and access is restricted by database security rules and app integrity checks. No method is completely secure, but we take reasonable technical and organizational measures to protect your data. If a data breach occurs, we will notify you and the relevant authority as required by law."),
("11. Children",
 "MeetIt is not intended for anyone under 18 and does not knowingly collect data from anyone under 18. If we learn that a user under 18 has created an account, we delete the account and its data."),
("12. Your Rights",
 f"Under Article 11 of the KVKK you have the right to: learn whether your data is processed; request information about it; learn the purpose of processing and whether it is used accordingly; know the third parties it is transferred to in Türkiye or abroad; request correction of incomplete or inaccurate data; request deletion or destruction; request that these actions be notified to third parties it was transferred to; object to an outcome against you resulting from analysis by automated systems; and claim compensation for damages caused by unlawful processing.\nSend your requests to {CONTACT}; we will respond within 30 days at the latest. If you are not satisfied with our response, you can file a complaint with the Turkish Personal Data Protection Authority."),
("13. Changes and Contact",
 f"This policy may be updated from time to time; significant changes are announced in the app. For questions: {CONTACT}"),
],
}
